version: "3.5"

services:
  jupyter:
    build:
      context: .
      dockerfile: local.Dockerfile
    # To use a different port of host, change the first 8888.
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: ./
        target: /home/jovyan/app
